%%%%%
%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Template for the papers to the case studies of Data Analytics
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[a4paper, 12pt, titlepage, headsepline, listof = totoc, bibliography = totoc, numbers = noenddot]{scrartcl}
\usepackage[left = 3cm, right = 2cm, top = 2.2cm, bottom = 3.5cm]{geometry} % spaces on the sides of the paper
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{amsfonts}
\usepackage{natbib}
\usepackage{scrpage2}
\usepackage{dsfont}
\usepackage{float}
\usepackage{amssymb}
\usepackage{caption}
\usepackage{subcaption}
\usepackage{chngcntr}

\frenchspacing

\usepackage{bbm}
\usepackage[labelfont=bf, font=footnotesize, tableposition=top]{caption}
\DeclareCaptionType[fileext=los,placement={!ht}]{listing}
%\usepackage{mdframed}
\usepackage{boxedminipage}
%\usepackage{chngcntr}
%\def \lstWidth {0.9}

\counterwithin{figure}{section}

\counterwithin{table}{section}

\newcommand{\eg}{e.\,g. }
\newcommand{\ie}{i.\,e. }
\newcommand{\cdf}{c.\,d.\,f. }
\newtheorem{thm}{Theorem}
\newtheorem{df}{Definition}
\newtheorem{lem}{Lemma}

%% path, where the figures are stored
\graphicspath{{./images/}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% design of the head of the report pages

\clearscrheadings                   	% clears all predefined formats voreingestellte Formatierungen
\pagestyle{scrheadings}			% use this style only on the actual text
\ohead{}		% writes your name on each side in the upper right corner
\automark{section}                  
\ihead{\headmark}				% automatically writtes the section name in the upper left corner
\cfoot{\pagemark}				% page number on the bottom (center)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% cover sheet

\title{\hrulefill \\ \vspace*{1cm} Case Studies\\\vspace*{0.5cm}
 "Data Analytics" \\ \vspace*{1cm}\hrulefill\vspace*{1.5cm}}
\subtitle{Topic\\\vspace*{1.5cm} Summer Term 2013\vspace*{1.5cm}}
\author{Andrey Chinnov, Sebastian Honermann, Carlos Zydorek}
%\institute{e-mail}

\usepackage{Sweave}
\begin{document}
\input{Report-concordance}
\thispagestyle{empty}
\maketitle

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% table of contents

\thispagestyle{empty}
\tableofcontents

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% the document itself

\newpage
\setcounter{page}{1}
\section{Introduction}

\subsection{Normality as a requirement for statistical methods}

Since the normal distribution has some convenient analytical properties, many statistical tests (\eg Two-sample z-test, One-sample t-test, or Chi-squared test for variance) are based on the assumption that data were drawn from a normal distribution. Furthermore, the central limit theorem for example is applied in many cases in practice. It states that, when under certain conditions a large number of observations stem from the same distribution, their mean will be approximately normally distributed. This statement holds independent of the original distribution the observations are drawn from. Hence, methods for testing sample data on normality are of major importance. 

This report aims at describing test methods for normality and conducting them on the Glass data set. Since the hypothesis of normality is rejected for most of the variables, this report is focused on methods for testing on univariate normal distribution. A transformation is applied to convert the data so that it complies with a normal distribution if possible. Nevertheless, a small part of this report deals with multivariate normal distribution.

Test methods for univariate normal distribution are introduced in section \ref{sec:preliminaries}. Furthermore, a transformation method and a technique for identifying multivariate (more precisely: bivariate) normally distributed data are described. In section \ref{sec:testing}, the introduced test methods are conducted on the original data as well as on the transformed data. Subsequently, the technique for checking on bivariate normal distribution is demonstrated on an example from the Glass data set. The findings are shortly concluded in section \ref{sec:conclusion}.

\subsection{The Glass data set}

The data set that is investigated in this report is the \texttt{Glass} data set from the R package \texttt{mlbench}, originally taken from the UCI Repository of Machine Learning Databases (Bache, K., Lichman, M. 2013). It contains 214 observations on 10 variables of glass specimen. The first variable is the refractive index (RI) followed by weight percent in the corresponding oxide of Sodium (Na), Magnesium (Mg), Aluminium (Al), Silicon (Si), Potassium (K), Calcium (Ca), Barium (Ba) and Iron (Fe). One variable specifies the type of glass as a class attribute. There are seven different types of glass but only six of them are contained in the present data set.

\newpage
\section{Preliminaries}\label{sec:preliminaries}

\subsection{The Normal Distribution}

The (univariate) normal distribution $N(\mu,\sigma^2)$ is defined to have the density

\[ Pr(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp (-\frac{1}{2\sigma^2}(x - \mu)^2) \]

where $\mu \in \mathbb{R}$ and $\sigma > 0$.

The univariate normal distribution is generalised by the multivariate normal distribution for higher
dimensions. $X$ has a multivariate normal distribution with mean vector $\mu$ and covariance $\Sigma$ > 0, i.e. $X \sim N_p(\mu,\Sigma)$, if

\[Pr(x) = |2\pi\Sigma|^{-1/2} \,\mbox{exp}\left\{-\frac{1}{2}(x-\mu)' \Sigma^{-1}(x-\mu)\right\}\]

Contour lines of the plot of a multivariate normal distribution are shaped elliptically. Those ellipsoids are centered at $\mu : \left\{x:(x-\mu)'\, \Sigma^{-1}(x-\mu) = c^2\right\}$ with some constant $c$.

A first approach to check a sample of several variables on multivariate normal distribution is to examine the plot on the appearance of elliptical contour lines. An exemplary contour plot is depicted in figure \ref{fig:plotMVNSim}. The data is simulated from the mulitvariate normal distribution with the parameters
\[\mu = \left(\begin{array}{c} 1\\ 2\end{array} \right), \quad \Sigma = \left[\begin{array}{cc} 27 & 15\\ 15 & 18\end{array} \right]\]
and a sample size of 500. The contour lines for this simulated sample are apparently elliptically shaped. Obviously, this graphical method only works for two variables respectively, \ie for bivariate distributions.

\begin{figure}[h!]
\centering
\includegraphics[width=0.8\textwidth]{report-plotMVNSim}
\caption{Data plot with contour lines of a simulated sample from a bivariate normal distribution}
\label{fig:plotMVNSim}
\end{figure}

\subsection{Test methods for normality}\label{sec:methods}

A statistical hypothesis test which tests empirical data on conformance with a certain distribution (or a family of distributions) is called a goodness of fit test. The null hypothesis usually refers to the position that the tested sample has been drawn from a population which is distributed according to the given distribution. Consequently, the alternative hypothesis states that the sample was drawn from a population of any other distribution. In every test, a certain method is used to calculate a test statistic from the data. If the test statistic exceeds a critical value which is computed for the particular distribution at a certain significance level, the null hypothesis is rejected. The p-value is the lowest significance level for which the null hypothesis would still be rejected. It can be interpreted as the probability of getting a result like the present one or an even more extreme result if the null hypothesis is true.

\subsubsection{Q-Q-plot}\label{sec:qq-theoretical}

Quantile-Quantile-Plots provide a graphical comparison of the quantiles of two probability distributions. The observed values are plotted against the quantiles of a theoretical distribution. To check for normality, the observations $x_1, \dots, x_n$ from a sample with size $n$ are ordered ( $x_{(1)} \le x_{(2)} \le \dots \le x_{(n)}$ ) and plotted against an assumed cumulative distribution function. Let $x_{(i)}$ denote the sample quantiles. For each sample quantile $x_{(j)}$ with $j$ observations to the left, the proportion of these $j$ observations is approximated by
\[ p_{(j)} = \frac{j - \frac{1}{2}} {n}\]
and the theoretical quantiles $q_{(j)}$ are defined by
\[ q_{(j)} = \Phi^{-1}(p_{(j)}) \]

where $\Phi$ is the cumulative distribution function of the standard normal distribution.

In the QQ-Plot these theoretical quantiles $q_{(j)}$ are then plotted against the sample quantiles $x_{(j)}$. Given a sufficient sample size, in the case of normally distributed data the observed quantiles will be linearly related to the theoretical normal distribution quantiles in the QQ-plot.

\subsubsection{Shapiro-Wilk test}\label{sec:shapiro-theoretical}

The Shapiro-Wilk test is a statistical procedure for testing a complete sample for normality. Basically, the test statistic, denoted as $W$, indicates correlation of the observed quantile values with the assumed cumulative distribution function quantiles and is therefore close to the idea of QQ-plots or probability-plots. 

\[ W = \frac{\sum \limits_{i=1}^n (a_i x_i)^2} {\sum \limits_{i=1}^n (x_i-\bar{x})^2}\]
where

$a_i$ denotes the normalized "best linear unbiased" coefficients and

$x_i$ denotes the ordered observations.

In detail, $W$ is obtained by dividing the best linear estimate of the slope of a linear regression of the ordered observations $x_i$ by the actual variance of the ordered observed sample values.

The resulting test statistic $W$ is then compared with a critial $W$-value for a given sample size $n$. The resulting significance level can be looked up in existing tables, however, most statistic software (including R) automatically determines the according p-value via the Monte Carlo method when displaying the test statistic $W$.

In general, the statistical power of tests decreases with smaller sample sizes. Compared to other statistical tests, like the Kolmogorov-Smirnov test or the Chi-Squared-Test, the Shapiro-Wilk test's statistical power decreases less with smaller samples. Since 4 of 6 glass type samples (glass type 3, 5, 6, and 7) have a size of $n$ < 50, the test result is quite interesting for the tests of the subdatasets.

In order to conduct the Shapiro-Wilk test in R the function \texttt{shapiro.test()} from the package \texttt{stats} is used.

In some cases all observations of certain variables are identical. In these cases the Shapiro-Wilk-Statistic is not applicable for these specific variables since the expression 
\[ \sum \limits_{i=1}^n (y_i - \bar{y})^2 \]
in the denominator, denoting the variance, sums up to 0. Tests can therefore only be run if such variables are excluded from the testing procedure.

\subsubsection{Pearson's chi-squared test}\label{sec:chisq-theoretical}
Pearson's chi-squared goodness of fit test is used to test whether data from a sample are distributed according to an arbitrary theoretical distribution. The main idea of this test is to divide the observations $x_1, \dots, x_n$ into several pairwise disjoint classes $C_1, \dots, C_K$ and compare the empirical frequencies within these classes to the theoretical frequencies, which are expected if the data complies to the hypothetical distribution.
\begin{figure}[h!]
\includegraphics[width=\textwidth]{report-chisqSampleHist}
\caption{Exemplary histrograms of a data sample, expected densities for a normal distribution with parameters estimated from the sample and a combined histogram of these both histograms.}
\label{fig:chisqSampleHist}
\end{figure}
If the histograms of the sample data and the expected densities are plotted together (see figure \ref{fig:chisqSampleHist}), the area of density that is not overlapped by both histograms can be understood as a kind of indicator for the likelihood that the sample is drawn from a population which is distributed according to the hypothetical distribution: The larger the non-overlapping area, the less likely it is that the sample is drawn from a population with the assumed distribution. However, the test statistic of the chi-squared test is calculated differently, namely by the sum of the squared differences between observed frequencies $O_k$ and expected frequencies $E_k$ divided by the expected frequencies for each class $k$ of the overall $K$ classes. Thus, the test statistic is calculated by
\[\chi^2 = \sum_{k=1}^{K}\frac{(O_k - E_k)^2}{E_k}\]
Larger differences of observed and expected values indicate a lower compliance to the assumed distribution. However, the addends are not weighted (neither by the size of a class nor by the frequencies within a class nor by any other means). Therefore, the class bounds should be chosen equidistant or in such a way that the classes contain preferably the same number of observations, or should be chosen according to similar reasonable rationales. The test statistic is approximately $\chi^2$-distributed with $K-1$ degrees of freedom -- the larger the sample size, the better the approximation. A sample size that is too small can be a reason for the approximation being insufficient. Moreover, for each parameter of the hypothetical distribution which is estimated from the data sample, one degree of freedom is lost; the number of estimated parameters is denoted by $p$. The test statistic is determined under the null hypothesis that the sample is distributed according to the assumed distribution and the chi-squared test is defined as
%\[\phantom{\quad \textrm{with}\ F=\chi^2_{K-1-p}} \delta(Y) = \mathbbm{1}_{\{\chi^2\, >\, F^{-1}(1-\alpha)\}} \quad \mbox{with}\ F=\chi^2_{K-1-p}\]
\[
  \phantom{\quad\mbox{with}\ F=\chi^2_{K-1-p}}
  \delta(Y) =
   \left\{ 
    \begin{array}{cll}
%\vspace{12pt}
                 1 & \mbox{if} \ \chi^2 > F^{-1}(1-\alpha)\\
                 0 & \mbox{otherwise}
    \end{array} 
   \right.
   \quad\mbox{with}\ F=\chi^2_{K-1-p}
\]
for a given significance level $\alpha$ where $Y$ is a multinomial distributed random variable denoting the counts of observations in each class with $Y_k = |\{i : X_i \in C_k\}|$.

A common requirement for a sufficient approximation demands the minimum number 
of observations in each class not to fall below five (Steel, R.G.D., Torrie, J.H. 1960, p. 350). 
Hence, marginal or even inner classes have to be unified in some cases in order to achieve a 
sufficient class size. 
%The following R-function is used here for this purpose.
%Further functions are needed for calculating the expected frequencies, the test
% statistic, and the result of the test (since the mean and the standard deviation are estimated from the sample, two degrees of freedom are additionally lost):
A drawback of Pearson's chi-squared test is its inconsistency caused by information reduction, \ie information about the data sample is lost in the process of categorising the observations in classes. As a consequence, different class bounds can lead to different test results. Furthermore, this test is rather suited for large sample sizes.

\subsubsection{Kolmogorov-Smirnov test}\label{sec:kolm-smir}
Like the other tests introduced in the previous chapters, the Kolmogorov-Smirnov (subsequently abbreviated as KS) is used for testing whether a given univariate sample $x=(x_1,x_2 \dots x_n)$ with unknown distribution $\mathbb{P}$ is distributed according to a completely determined distribution $\mathbb{P}_0$. Based on the test a decision is made between the following two hypotheses:
\[\begin{array}{rcl}
H_0 & : & \mathbb{P} = \mathbb{P}_0,\\
H_1 & : & \mathbb{P} \ne \mathbb{P}_0.
\end{array}\]
This decision is made according to the KS test
statistics and a given significance level $\alpha$.

\begin{df}
For a given univariate sample $x=(x_1, x_2, \dots, x_n)$ the function
\[F_n=\frac{1}{n}\sum_{i=1}^n \mathbbm{1}_{\{x_i\le x\}}\] is called empirical
cumulative distribution function (\cdf), where $\mathbbm{1}_{\{x_i\le x\}}$ is an
indicator function defined as follows: $\mathbbm{1}_{\{x_i\le x\}}(x)=\left\lbrace 
\begin{array}{cll}
                 1 & \mbox{if} \ x_i\le x\\
                 0 & \mbox{otherwise}.
\end{array} 
\right.$
\end{df}
The exemplary graph of such a function is depicted in the Figure
\ref{fig:empiricFunc}. 

The main idea of the KS test is the analysis of the difference between the given
cumulative distribution function (\cdf) $F$ and the empirical \cdf $F_n$. Since
both theoretical and empirical functions belong to normed space of bounded
functions $\mathbb{B}(\mathbb{R})$ (all values are between 0 and 1), this difference can be measured as
a distance $\|F_n-F\|_{\infty}=\sup_{x \in \mathbb{R}}|F_n(x)-F(x)|$. Figure
\ref{fig:empiricTeorFunc} illustrates the calculated distance between the
empirical \cdf and the theoretical normal \cdf with respect to the given parameters \textit{sample mean}
and \textit{sample variance}. 
%\begin{figure}[h!]
%\includegraphics[width=\textwidth]{report-empiricFunc}
%\caption{Exemplary empirical \cdf of a data sample.}
%\label{fig:empiricFunc}
%\end{figure}


%\begin{figure}[h!]
%\includegraphics[width=\textwidth]{report-empiricTeorFunc}
%\caption{Exemplary empirical \cdf of a data sample.}
%\label{fig:empiricTeorFunc}
%\end{figure}
\begin{figure}[H]
\centering
\begin{subfigure}{.5\textwidth}
  \centering
  \includegraphics[width=\linewidth]{report-empiricFunc}
  \vspace{-1cm}
  \caption{}
  \label{fig:empiricFunc}
\end{subfigure}%
\begin{subfigure}{.5\textwidth}
  \centering
  \includegraphics[width=\linewidth]{report-empiricTeorFunc}
  \vspace{-1cm}
  \caption{}
  \label{fig:empiricTeorFunc}
\end{subfigure}
\caption{Empirical \cdf for Sodium (Na) vector (a) and theoretical normal \cdf with
sample mean and sample variance (b)}
\label{fig:commonFigureKStest}
\end{figure}

The KS test statistics is defined as follows:
\[D_n = \sqrt{n}\cdot \sup_{x \in \mathbb{R}}|F_n(x)-F(x)|.\]
If value $D_i$ is considered for different $1\le i\le n$, then the sample
$\hat{D}_n=(D_1,\dots,D_n)$ is obtained that also complies with some
distribution $\mathbb{D}_n$.
It can be shown that if hypothesis $H_0$ is true, then this distribution does not depend on the \cdf $F$
and therefore can be tabulated. Moreover, Kolmogorov proved that if $n$ is large
enough, the distribution function of $\mathbb{D}_n$ can be approximated by
Kolmogorov-Smirnov distribution function
$H(t)=1-2\sum_{i=1}^{\infty}(-1)^{i-1} \exp^{-2i^2t^2}$, \ie for each positive
value $t$ the probability $P(D_n\le t)\to H(t)$ when $n \to \infty$. More
details can be found in the textbook (DeGroot, Morris, H., Mark, J. 2003).

The KS test uses the decision rule
\[ \delta = 
\left\{
\begin{array}{rcl}
H_0&:& D_n\le c\\
H_1&:& D_n> c
\end{array}
\right.,
\]
where the critical value $c$ depends on the significance level $\alpha$ and
can be calculated from the following equations:
\[\alpha = P(\delta \ne H_0|H_0)=P(D_n>c|H_0)=1-P(D_n\le c|H_0)\approx 1-H(c).\]
As mentioned above the last expression can only be considered appriximately equal when $n$ is
relatively high. Otherwise the table values for $\mathbb{D}_n$ distribution
should be used. Hence, $c\approx H^{-1}(1-\alpha)$.

Although the KS test is commonly used, it has a huge drawback. Namely it
considers only completely defined theoretical \cdf. When testing for normality 
both parameters $\mu$ and $\sigma^2$ have to be predefined. But usually they are
a priori unknown when a sample is going to be tested. Of course it can be
managed by assigning sample mean and sample variance as unknown parameters (and
initial KS test suggests to do that) but they are not always the best choice.
The following example of the Sodium (Na) distribution illustrates this proposition. 

For the univariate Sodium (Na) sample of 70 observations the sample mean
$\bar{\mu}=$13.2423 and the sample variance $\bar{\sigma^2}=$
0.2493 are calculated. For these values the
theoretical c.d.f. is determined (Figure \ref{fig:empiricTeorFunc}). Then
the value of KS statistic is calculated: $D_n=\sqrt{n}\cdot
\sup_x|F_n(x)-F(x)|=$2.2493.
The critical value for the significance level $\alpha=0.01$ is equal to
$c=H^{-1}(1-\alpha)$=1.6276. 
%To calculate this value the following $R$ functions are used:

Since $D_n>c$, the null hypothesis is rejected by the KS test. But that does not mean that the sample is not normally distributed. It only means that the hypothesis is rejected for the normal distribution with these specific parameters sample mean and sample variance. 

In order to manage this issue, the KS test is improved by solving the following
optimisation problem \[KS(\mu,\sigma^2)=\sup_{x \in
\mathbb{R}}|F_n(x)-F(x,\mu,\sigma^2)|\to \min.\]
When the new values $\hat{\mu}$ and $\hat{\sigma^2}$ that minimise the value
$KS(\mu,\sigma^2)$ are found, the general KS test is performed with respect to
these values of parameters. For solving this optimisation problem the following
$R$ code is used:

\begin{Schunk}
\begin{Sinput}
 KS= function(param) {
 	#discretization of a line segment
 	seq = seq(from = min(dat)-0.2, to = max(dat)+0.2, length.out=1000)
 	#values of empirical c.d.f.
 	empdat = sapply(seq, function(x) {empiric(x,dat)})
 	#values of theoretical c.d.f.
 	theordat = pnorm(seq,param[1],abs(param[2]))
 	#difference between the values
 	dif=theordat-empdat
 	absdiff=abs(dif)
 	max(absdiff)
 }
 #optim is a predifined R function in stats package
 #defalut method of optimisation is Nelder and Mead (1965)
 KSoptim = optim(c(mean,Cov),KS)
 KSoptim$par
\end{Sinput}
\begin{Soutput}
[1] 13.1769501  0.4682486
\end{Soutput}
\begin{Sinput}
 KSoptim$value
\end{Sinput}
\begin{Soutput}
[1] 0.07870673
\end{Soutput}
\end{Schunk}
These new parameters
$\hat{\mu}=$13.1770 and
$\hat{\sigma}^2=$0.4682 are taken as
parameters of a new theoretical normal \cdf and a new distance is calculated
(Figure \ref{fig:improvedKS}). 
\begin{figure}[H]
\includegraphics[width=\textwidth]{report-improvedKS}
\caption{Normal \cdf with optimised parameters in comparison to the old \cdf
with sample mean and sample variance.}
\label{fig:improvedKS}
\end{figure}

The new value of the KS statistics is $D_n=\sqrt{n}\sup_{x \in
\mathbb{R}}|F_n(x)-F(x,\hat{\mu},\hat{\sigma}^2)|=$0.6585
which is smaller than the critical value $c=$1.6276. Therefore, the null
hypothesis $H_0$ cannot further be rejected by KS-test. For all further samples, the improved KS
test is used. 
%It was implemented in $R$ and has the following code.


The approximation problem with the $H$ function remains in the improved KS test
as well. Therefore this approximation is only applicable when 
the sample size is relatively high. Otherwise, the tabular values for
$\mathbb{D}_n$ distribution should be used. 



\subsection{Box-Cox-transformation}\label{sec:boxcox-theory}

If data are not normally distributed, it can still be transformed to fit to a normal distribtion in some cases. One possibility is the Box-Cox-transformation. It is a family of parameterised power tranformations:
\[
  \phantom{\quad\mbox{for}\ x > 0}
   x^{(\lambda)} =
   \left\{ 
    \begin{array}{cl}
%\vspace{12pt}
                 \frac{x^\lambda - 1}{\lambda} & \lambda \neq 0\\
                 \ln(x) & \lambda = 0
    \end{array}
   \right.
   \quad\mbox{for}\ x > 0
\]
The optimal parameter for specific observations $x_1, \dots, x_n$ can be determined by a maximum-likelihood estimation, maximising the log likelihood
\[
\begin{array}{l}
\vspace{12pt}
   l(\lambda) = - \frac{n}{2}\ln\left[\frac{1}{n}\sum_{j=1}^{n}(x_j^{(\lambda)} - \overline{x^{(\lambda)}})^2\right] + (\lambda - 1) \sum_{j=1}^{n}\ln(x_j)\\
   \mbox{with}\ \overline{x^{(\lambda)}} = \frac{1}{n} \sum_{j=1}^{n}x_j^{(\lambda)}
\end{array}
\]
However, a Box-Cox-transformation does not ensure that the data is normally distributed thereafter. One reason that a sample cannot be properly transformed could be that it is not unimodal. Histograms and QQ-plots of a sample from a unimodal distribution are depicted in figure \ref{fig:transformationUnimodal}. Data that is generated from a Weibull distribution can be transformed to approximately normally distributed values quite well as can be recognised by the histogram and the QQ-plot. In contrast, it is not possible to properly transform a sample that is combined from two different distributions (here with different scale parameters of the Weibull distribution) as shown in figure \ref{fig:transformationBimodal}. By the combination of two samples with different mean values a bimodal sample emerges preventing the underlying data to be transformed to a unimodal sample (namely a normally distributed sample) by a simple function. Furthermore, noisy data is not suited for Box-Cox-transformation either because the Box-Cox-function is applied on the whole sample (and not only the "noisy parts").
\newpage
\phantom{.}
\vfill

\begin{figure}[h!]
\includegraphics[width=\textwidth]{report-transformationUnimodal}
\caption{Histograms and QQ-plots of a Weibull(1, 1) simulated sample of size 500 and of the Box-Cox-transformed data}
\label{fig:transformationUnimodal}
\end{figure}

\vfill

\newpage
\phantom{.}
\vfill

\begin{figure}[h!]
\includegraphics[width=\textwidth]{report-transformationBimodal}
\caption{Histograms and QQ-plots of a mixed sample composed of a Weibull(5, 1) simulated sample and a Weibull(5, 4) simulated sample (each of size 250) and of the Box-Cox-transformed data}
\label{fig:transformationBimodal}
\end{figure}

\vfill


\newpage
\section{Testing the data sample for normality}\label{sec:testing}

\subsection{Testing original data}


The test methods for normality that were introduced in section \ref{sec:methods} are now applied on the glass data set. For each method, the whole sample is tested first. Since it can be assumed that the different glass types are distinct in terms of the underlying distribution of variable values, the tests are conducted on the individual types as well (where applicable). It appears reasonable to skip particular variables whose values predominantly consist of zeros (more than 50\,\% of the observations, see table \ref{tab:zeros}) because this indicates that those variables are not normally distributed anyway (moreover, this can lead to complications for some methods).

\begin{table}[h!]
\centering
\begin{tabular}{|cl|}
\hline
type & skipped variables\\
\hline
1 & Ba\\
2 & Ba\\
3 & Ba, Fe\\
5 & Ba, Fe\\
6 & K, Ba, Fe\\
7 & Mg\\
\hline
\end{tabular}
\caption{Skipped variables for the particular glass types due to too many zero values}
\label{tab:zeros}
\end{table}

\subsubsection{Q-Q-plot}\label{sec:qq-original}
For the graphical analysis the quantiles for all elements in the glass-dataset where plotted for the whole dataset and for each glass type separately. As depicted in Figure \ref{fig:QQfull}, the QQ-Plots for the five variables recursive index (RI), Sodium (Na), Aluminium (Al), Silicon (Si), and Calcium (Ca) do suggest that linear relationships could be assumed. The other four variables Magnesium (Mg), Barium (Ba), Potassium (K), and Iron (Fe) clearly are not linearly related to the hypothetical quantiles.

\begin{figure}[h!]
\centering
\includegraphics[width=\textwidth]{report-QQfull}
\caption{Exemplary QQ-Plots from the full data sample}
\label{fig:QQfull}
\end{figure}


\begin{figure}[h!]
\centering
\includegraphics[width=\textwidth]{report-QQsamples}
\caption{Exemplary QQ-Plots from Glass Type 1 where a graphical inspection does not suggest a linear relationship}
\label{fig:QQsamples}
\end{figure}

The graphical comparison of the subdatasets shows that for most of the cases there seems to be no linear relationship between the theoretical normally distributed quantiles and the observed values. For some cases in the subdatasets, however, based on a graphical inspection a linear relationship can be assumed given some outliers. As shown in Figure \ref{fig:QQsampleslin1} Magnesium (Mg), Aluminium(Al), and Silicon (Si) in glass type 1 and Ca in glass type 7 show approximately linear relationships with just a few outliers. For some observations (e.g. Na in glass type 5 and RI in glass type 6 in Figure \ref{fig:QQsampleslin2}) a linear relationship seems to be plausible, however, the total number of observations in these cases is considered too small to make conclusions about a hypothetical linear relationship (glass type 5: $n$ = 13; glass type 6: $n$ = 9).

\begin{figure}[h!]
\centering
\includegraphics[width=\textwidth]{report-QQsampleslin1}
\caption{QQ-Plots of the cases where a linear relationship seems plausible}
\label{fig:QQsampleslin1}
\end{figure}

%\begin{figure}[h!]
%\centering
%\includegraphics[width=\textwidth]{report-QQsampleslin2}
%\caption{QQ-Plots of possible linear relationships with very small sample sizes}
%\label{fig:QQsampleslin2}
%\end{figure}

%\begin{figure}[h!]
%\centering
%\includegraphics[width=\textwidth]{report-QQsampleslin2}
%\caption{QQ-Plots of possible linear relationships with very small sample sizes}
%\label{fig:QQsampleslin2}
%\end{figure}

\begin{figure}[h!]
\centering
\begin{subfigure}{.5\textwidth}
  \centering
  \includegraphics[width=\linewidth]{report-QQsampleslin2a}
  \vspace{-1cm}
  \caption{}
  \label{fig:QQsampleslin2a}
\end{subfigure}%
\begin{subfigure}{.5\textwidth}
  \centering
  \includegraphics[width=\linewidth]{report-QQsampleslin2b}
  \vspace{-1cm}
  \caption{}
  \label{fig:QQsampleslin2b}
\end{subfigure}
\caption{QQ-Plots of possible linear relationships with very small sample sizes}
\label{fig:QQsampleslin2}
\end{figure}

\subsubsection{Shapiro-Wilk test}\label{sec:shapiro-original}
Performing the Shapiro-Wilk test on the complete dataset at hand, according to the p-values the null hypothesis (the data the sample is taken from is normally distributed) is rejected for all the elements.
Testing the different glass types separately, the p-values of majority of the variables are still very small. Consequently, the null hypotheses can be rejected for almost all separate cases. For a total 16 cases (over all 6 glass types) the test returned a p-value above or equal to the set alpha-level of 1\, \% (Tables \ref{tab:testrestype1SW} to \ref{tab:testrestype7SW}). However, the majority of the cases for which the null hypothesis holds stems from the three subdatasets containing significantly less observations (Tables \ref{tab:testrestype3SW} to \ref{tab:testrestype6SW}). For glass type 1 $H_0$ is rejected for all the variables (see Table \ref{tab:testrestype1SW}). For glass type 2 it only holds for Aluminium (Al) and for glass type 7 only for Aluminium (Al) and Barium (Ba) (see Tables \ref{tab:testrestype2SW} and \ref{tab:testrestype7SW}).
More than 80\, \% of the total rejections in the 6 tests (13 out of 16) stem from the three smaller subdatasets glass type 3, glass type 5, and glass type 6. These results raise the question if the low number of rejections is due to the smaller sample size in these cases. Looking only at the glass types 1, 2, and 7, a normal distribution can be rejected for most of the cases.



\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.87 & 0.01 & NA & 1.0766713449726e-12 & yes\\ 
Na & 0.95 & 0.01 & NA & 3.4655430546966e-07 & yes\\ 
Mg & 0.7 & 0.01 & NA & < 1.0e-15 & yes\\ 
Al & 0.94 & 0.01 & NA & 2.08315629600399e-07 & yes\\ 
Si & 0.92 & 0.01 & NA & 2.17503176825416e-09 & yes\\ 
K & 0.44 & 0.01 & NA & < 1.0e-15 & yes\\ 
Ca & 0.79 & 0.01 & NA & < 1.0e-15 & yes\\ 
Ba & 0.41 & 0.01 & NA & < 1.0e-15 & yes\\ 
Fe & 0.65 & 0.01 & NA & < 1.0e-15 & yes\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the whole data sample}
\label{tab:testresFullSW}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.88 & 0.01 & NA & 6.36192013015468e-06 & yes\\ 
Na & 0.95 & 0.01 & NA & 0.00459078607995831 & yes\\ 
Mg & 0.82 & 0.01 & NA & 8.02702432879544e-08 & yes\\ 
Al & 0.9 & 0.01 & NA & 5.42971629496434e-05 & yes\\ 
Si & 0.91 & 0.01 & NA & 0.000117060780025464 & yes\\ 
K & 0.77 & 0.01 & NA & 3.14049093233846e-09 & yes\\ 
Ca & 0.93 & 0.01 & NA & 0.00103561283726753 & yes\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on type 1 glass}
\label{tab:testrestype1SW}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.72 & 0.01 & NA & 1.08673299441225e-10 & yes\\ 
Na & 0.9 & 0.01 & NA & 1.82678898797777e-05 & yes\\ 
Mg & 0.64 & 0.01 & NA & 2.38749395349814e-12 & yes\\ 
Al & 0.97 & 0.01 & NA & 0.0591136375348645 & no\\ 
Si & 0.88 & 0.01 & NA & 3.75379726827069e-06 & yes\\ 
K & 0.84 & 0.01 & NA & 1.54088105687157e-07 & yes\\ 
Ca & 0.67 & 0.01 & NA & 7.17521765879123e-12 & yes\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on type 2 glass}
\label{tab:testrestype2SW}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.83 & 0.01 & NA & 0.00554477459285981 & yes\\ 
Na & 0.95 & 0.01 & NA & 0.42694777005566 & no\\ 
Mg & 0.93 & 0.01 & NA & 0.2109500928052 & no\\ 
Al & 0.95 & 0.01 & NA & 0.427341606866833 & no\\ 
Si & 0.89 & 0.01 & NA & 0.0442493392726916 & no\\ 
K & 0.76 & 0.01 & NA & 0.000539393334400821 & yes\\ 
Ca & 0.92 & 0.01 & NA & 0.147928579200966 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on type 3 glass}
\label{tab:testrestype3SW}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.9 & 0.01 & NA & 0.121477380963252 & no\\ 
Na & 0.88 & 0.01 & NA & 0.0623633158882554 & no\\ 
Mg & 0.75 & 0.01 & NA & 0.00177054101772265 & yes\\ 
Al & 0.79 & 0.01 & NA & 0.00461960768904678 & yes\\ 
Si & 0.9 & 0.01 & NA & 0.134368361027878 & no\\ 
K & 0.59 & 0.01 & NA & 5.18709751538094e-05 & yes\\ 
Ca & 0.85 & 0.01 & NA & 0.0259126903932093 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on type 5 glass}
\label{tab:testrestype5SW}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.69 & 0.01 & NA & 0.00107643062031905 & yes\\ 
Na & 0.7 & 0.01 & NA & 0.00125686447739013 & yes\\ 
Mg & 0.8 & 0.01 & NA & 0.0192642436690133 & no\\ 
Al & 0.88 & 0.01 & NA & 0.141250903376574 & no\\ 
Si & 0.78 & 0.01 & NA & 0.0119496897911561 & no\\ 
Ca & 0.92 & 0.01 & NA & 0.404068518356898 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on type 6 glass}
\label{tab:testrestype6SW}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.82 & 0.01 & NA & 0.000228738547251759 & yes\\ 
Na & 0.87 & 0.01 & NA & 0.00202603090330278 & yes\\ 
Al & 0.96 & 0.01 & NA & 0.289110586782862 & no\\ 
Si & 0.78 & 0.01 & NA & 3.1655457932838e-05 & yes\\ 
Ca & 0.72 & 0.01 & NA & 3.98543372675882e-06 & yes\\ 
Ba & 0.91 & 0.01 & NA & 0.0206467993594091 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on type 7 glass}
\label{tab:testrestype7SW}
\end{table}


\subsubsection{Pearson's chi-squared test}

As mentioned in section \ref{sec:chisq-theoretical}, Pearson's chi-squared test is not suited for rather small sample sizes because of the approximation via the chi-squared distribution. Concerning the given data, the samples of type 3 glass (17 observations), type 5 glass (13 observations) and type 6 glass (9 observations) are not large enough to ensure a viable test result. Hence, the data belonging to those types will not be considered for separate tests. However, it will remain in the overall data sample of all types. The minimum size of observations in each class is set to five and the number of initial classes (\ie number of classes before unifying) will be ten. The first tests are conducted on the whole data set for each variable. The results are shown in table \ref{tab:chi-full}. For two variables, it is not possible to determine a test result with the given parameters: The observations of the variables Potassium (K) and Barium (Ba) are divided only into three classes respectively after the unification of classes in order to fulfill the requirement of minimum class size. Since one degree of freedom is subtracted always and two degrees of freedom are subtracted for the estimation of the mean value and the standard deviation, zero degrees of freedom remain and so the critical value cannot be calculated. For each of the other variables, the hypothesis of normality is clearly rejected for the given significance level.

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 64.95 & 0.01 & 13.28 & 2.64011035255862e-13 & yes\\ 
Na & 36.99 & 0.01 & 13.28 & 1.80797974702607e-07 & yes\\ 
Mg & 158.3 & 0.01 & 11.34 & < 1.0e-15 & yes\\ 
Al & 27.2 & 0.01 & 9.21 & 1.24084046404516e-06 & yes\\ 
Si & 38.85 & 0.01 & 13.28 & 7.4876188027595e-08 & yes\\ 
K & 95.97 & 0.01 & NA & NA & NA\\ 
Ca & 131.13 & 0.01 & 13.28 & < 1.0e-15 & yes\\ 
Ba & 31.37 & 0.01 & NA & NA & NA\\ 
Fe & 70.96 & 0.01 & 13.28 & 1.4210854715202e-14 & yes\\ \hline \end{tabular}\caption{Test results of the chi-squared test on the whole data sample with ten initial classes}
\label{tab:chi-full}
\end{table}

The results for type 1 glass (table \ref{tab:chi-type1}) are slightly different; in this case, the results can be determined for each variable (except for Barium (Ba), which has been dropped beforehand) and the hypothesis of normality is rejected for each variable but Sodium (Na). The p-value for Sodium is comparably high amounting to approximately 0.52. It is well recognisable that the observed class frequencies for Sodium fluctuate around the expected class frequencies under the hypothesis of a normal distribution with the according parameters (table \ref{tab:testresChisqFreqNaType1}). The good compliance of empirical and hypothetical data for this variable is illustrated in figure \ref{fig:chisqType1Na}. In general, the p-values for this part of the sample are higher than those for the whole sample.

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 28.01 & 0.01 & 9.21 & 8.26265138420545e-07 & yes\\ 
Na & 3.25 & 0.01 & 13.28 & 0.51688441877949 & no\\ 
Mg & 18.81 & 0.01 & 6.63 & 1.44068580684165e-05 & yes\\ 
Al & 23.55 & 0.01 & 11.34 & 3.10284613768141e-05 & yes\\ 
Si & 23.68 & 0.01 & 13.28 & 9.26014020323773e-05 & yes\\ 
K & 114.86 & 0.01 & 11.34 & < 1.0e-15 & yes\\ 
Ca & 22.58 & 0.01 & 15.09 & 0.000405198755082603 & yes\\ 
Fe & 18.65 & 0.01 & 9.21 & 8.91413549507503e-05 & yes\\ \hline \end{tabular}\caption{Test results of the chi-squared test on type 1 glass with ten initial classes}
\label{tab:chi-type1}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|c|cc|} \hline class & \multicolumn{2}{c|}{frequencies}\\ (interval) & observed & expected\\ \hline ]12.4, 12.8] & 15 & 13.15\\ 
]12.8, 13] & 12 & 8.81\\ 
]13, 13.2] & 9 & 10.68\\ 
]13.2, 13.4] & 11 & 11.04\\ 
]13.4, 13.6] & 8 & 9.74\\ 
]13.6, 14] & 9 & 12.06\\ 
]14, 14.8] & 6 & 4.52\\ \hline \end{tabular}\caption{Observed end expected frequencies of items in the classes for the variable Sodium of type 1 glass}
\label{tab:testresChisqFreqNaType1}
\end{table}

\begin{figure}[h!]
\centering
\includegraphics[width=0.8\textwidth]{report-chisqType1Na}
\caption{Histogram of observed densities (red) and expected densities (blue) within the classes for the variable Sodium of type 1 glass}
\label{fig:chisqType1Na}
\end{figure}

The test results for observations of type 2 glass are summarised in table \ref{tab:chi-type2}. The null hypothesis is rejected for all variables except for Aluminium (Al) and Silicon (Si). The p-values for these variables are however rather small (approximately 0.02 and 0.04).

\begin{table}[h]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 27.92 & 0.01 & 9.21 & 8.6430973300633e-07 & yes\\ 
Na & 8.2 & 0.01 & 6.63 & 0.00418393039163056 & yes\\ 
Mg & 66.57 & 0.01 & 6.63 & < 1.0e-15 & yes\\ 
Al & 9.41 & 0.01 & 11.34 & 0.024332262426528 & no\\ 
Si & 6.24 & 0.01 & 9.21 & 0.0441247638253744 & no\\ 
K & 41.06 & 0.01 & 6.63 & 1.47495904379014e-10 & yes\\ 
Ca & 71.68 & 0.01 & 9.21 & < 1.0e-15 & yes\\ 
Fe & 16.75 & 0.01 & 11.34 & 0.000794876178432768 & yes\\ \hline \end{tabular}\caption{Test results of the chi-squared test on type 2 glass with ten initial classes}
\label{tab:chi-type2}
\end{table}

For the observations of type 7 glass, test results (table \ref{tab:chi-type7}) are only available for the variable Aluminium (Al). Due to the small sample size of 29 observations, most of the initial classes are joined so that no degree of freedom remains for the chi-squared distribution function. The hypothesis of normality is not rejected for the data of Aluminium.

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 19.93 & 0.01 & NA & NA & NA\\ 
Na & 1.4 & 0.01 & NA & NA & NA\\ 
Al & 3.42 & 0.01 & 6.63 & 0.0644860281274806 & no\\ 
Si & 4.84 & 0.01 & NA & NA & NA\\ 
K & 13.14 & 0.01 & NA & NA & NA\\ 
Ca & 11.93 & 0.01 & NA & NA & NA\\ 
Ba & 0.2 & 0.01 & NA & NA & NA\\ \hline \end{tabular}\caption{Test results of the chi-squared test on type 7 glass with ten initial classes}
\label{tab:chi-type7}
\end{table}

As mentioned in section \ref{sec:chisq-theoretical}, Pearson's chi-squared test is inconsistent when the number or bounds of classes are changed. This inconsistency can also be observed with the present data set. The test have also been conducted with 30 initial classes each (see tables \ref{tab:chi-full-30} to \ref{tab:chi-type7-30} in the appendix) with partly different results. Whereas with ten initial classes, there are not enough classes left for most of the variables of type 7 glass to be tested, the data is divided in a sufficient number of classes when using 30 initial classes. Above all, the null hypothesis is not rejected for Aluminium (Al) of type 2 glass with ten initial classes but it is rejected with 30 initial classes while the opposite is true for Sodium (Na). In general, the p-values can alternate much with different classes; so the rather high p-value for Sodium of type 1 glass ($\sim$ 0.52) with ten initial classes decreases to approximately 0.02 with 30 initial classes. On the contrary, the p-value for Aluminium of type 7 glass ($\sim$ 0.06) increases to approximately 0.19. These different impacts on the test results are due to two opposing effects: First, with more classes there are more degrees of freedom for the chi-squared distribution and thus the critical value increases. Second, the test statistic tends to increase as well because the observations have to fit to smaller classes more precisely; or in other words, observations may be distorted (relatively to the hypothetical expectations) within a large class so that differences between empirical and hypothetical data do not raise the test statistic as much as the same observations would if they were divided into smaller classes (making the distortion "measurable").

\subsubsection{Kolmogorov-Smirnov test}



First and foremost, the Kolmogorov-Smirnov test is conducted on the whole dataset for each variable. As depicted in table \ref{tab:KS-full}, the results indicate that only for Magnesium (Mg), Potassium (K), Barium (Ba), and Iron (Fe) $H_0$ can be rejected. For all other variables the hypothesis that the data the sample stems from is normally distributed cannot be rejected.

Performing the test on the subclasses type 1 glass, type 2 glass, and type 7 glass for each variable, the results further support the notion that data in the different subclasses is normally distributed.
While for type 1 glass $H_0$ can only be rejected for Potassium (K) and Iron (Fe) (see table \ref{tab:KS-type1}) and for type 2 glass $H_0$ can only be rejected for Iron (Fe) (see table \ref{tab:KS-type2}), the tests on type 7 glass show that for none of the contained elements the null hypothesis can be rejected at the 1\, \% significance level.


\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 1.34 & 0.01 & 1.63 & 0.0561963016778131 & no\\ 
Na & 0.87 & 0.01 & 1.63 & 0.43825271603342 & no\\ 
Mg & 2.94 & 0.01 & 1.63 & 6.18457917100912e-08 & yes\\ 
Al & 0.84 & 0.01 & 1.63 & 0.474757887353829 & no\\ 
Si & 0.96 & 0.01 & 1.63 & 0.314710019077325 & no\\ 
K & 2.14 & 0.01 & 1.63 & 0.000212776619708754 & yes\\ 
Ca & 1.33 & 0.01 & 1.63 & 0.057710602872685 & no\\ 
Ba & 2.6 & 0.01 & 1.63 & 2.75476085742632e-06 & yes\\ 
Fe & 4.68 & 0.01 & 1.63 & < 1.0e-15 & yes\\ \hline \end{tabular}\caption{Test results of the improved KS test on the whole data sample}
\label{tab:KS-full}
\end{table}


\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 1.31 & 0.01 & 1.63 & 0.0630043926883292 & no\\ 
Na & 0.66 & 0.01 & 1.63 & 0.77871853343362 & no\\ 
Mg & 0.49 & 0.01 & 1.63 & 0.967729719418776 & no\\ 
Al & 0.92 & 0.01 & 1.63 & 0.366854549713195 & no\\ 
Si & 1.06 & 0.01 & 1.63 & 0.208027646546284 & no\\ 
K & 1.73 & 0.01 & 1.63 & 0.00491847745617136 & yes\\ 
Ca & 0.84 & 0.01 & 1.63 & 0.48064266616439 & no\\ 
Fe & 2.65 & 0.01 & 1.63 & 1.63244296669252e-06 & yes\\ \hline \end{tabular}\caption{Test results of the improved KS test on type 1 glass}
\label{tab:KS-type1}
\end{table}



\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 1.08 & 0.01 & 1.63 & 0.190264315474967 & no\\ 
Na & 0.49 & 0.01 & 1.63 & 0.969807662718898 & no\\ 
Mg & 1.37 & 0.01 & 1.63 & 0.0477938096655182 & no\\ 
Al & 0.64 & 0.01 & 1.63 & 0.807950624660872 & no\\ 
Si & 0.55 & 0.01 & 1.63 & 0.918823986509849 & no\\ 
K & 1.18 & 0.01 & 1.63 & 0.125440771961193 & no\\ 
Ca & 1.43 & 0.01 & 1.63 & 0.0327944325987 & no\\ 
Fe & 2.5 & 0.01 & 1.63 & 7.20083142169425e-06 & yes\\ \hline \end{tabular}\caption{Test results of the improved KS test on type 2 glass}
\label{tab:KS-type2}
\end{table}



\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.67 & 0.01 & 1.63 & 0.767837508224946 & no\\ 
Na & 0.52 & 0.01 & 1.63 & 0.951658259816235 & no\\ 
Al & 0.49 & 0.01 & 1.63 & 0.968495966845634 & no\\ 
Si & 0.56 & 0.01 & 1.63 & 0.915628110530136 & no\\ 
K & 1.43 & 0.01 & 1.63 & 0.0340401962712393 & no\\ 
Ca & 0.56 & 0.01 & 1.63 & 0.91558957374917 & no\\ 
Ba & 0.76 & 0.01 & 1.63 & 0.61288183743927 & no\\ \hline \end{tabular}\caption{Test results of the improved KS test on type 7 glass}
\label{tab:KS-type7}
\end{table}

\subsection{Testing transformed data}\label{sec:testing-transformed-data}

The same tests are now conducted on the data that have been Box-Cox-transformed with a parameter that is estimated by the maximum likelihood method. For some variables, an estimation is not possible because the algorithm does not converge or, as in most cases, not all of the observations of one variable are strictly positive.
\subsubsection{Q-Q-plot}\label{sec:qq-transformed}

Before testing statistically, the results of the transformation can be examined graphically by again plotting the quantiles of the transformed data and comparing these plots with the QQ-plots from the original data in section \ref{sec:qq-original}. For some of the elements in the dataset the transformation leads to a slight approximation towards normality (figure \ref{fig:QQtrans}). However, for rather complicated cases (e. g. where several distributions seem to be combined) the transformation appearently does not produce normally distributed data (figure \ref{fig:QQtransno}). In these cases the initial distribution is not unimodal and therefore the Box-Cox-transformation is not very helpful (see section \ref{sec:boxcox-theory} for a detailed explanation).

\begin{figure}[h!]
\centering
\includegraphics[width=\textwidth]{report-QQtrans}
\caption{QQ-Plots of the cases where the transformation shows slight approximations to normality}
\label{fig:QQtrans}
\end{figure}

\begin{figure}[h!]
\centering
\includegraphics[width=\textwidth]{report-QQtransno}
\caption{QQ-Plots of the non-unimodal cases where the transformation does not lead to normal distributions}
\label{fig:QQtransno}
\end{figure}


\subsubsection{Shapiro-Wilk test}\label{sec:shapiro-transformed}

When performing the Shapiro-Wilk test on the whole transformed data, at the first glance the transformation does not seem to have had the desired impact on the data. As displayed in table \ref{tab:testresFullSWtrans} for all elements the Null Hypothesis is rejected. Although the p-values increased, they are still below the 1\, \% significance level, so there is no fundamental difference to the results from testing the original data.

However, proceeding analogously to section \ref{sec:shapiro-original} and testing the different glass types separately, these separate results reveal some improvements.

Glass type 1 shows the largest number of improvements, since in the original dataset the Null hypothesis was rejected for all variables. The test results of the transformed type 1 data from table \ref{tab:testrestype1SWtrans} show significantly increased p-values. For the three variables Sodium (Na), Aluminium (Al), and Calcium (Ca) now a normal distribution cannot be rejected any more.

For the glass types 2 and 3 there are no changes in the number of rejections at the 1\, \% significance level (tables \ref{tab:testrestype2SWtrans} and \ref{tab:testrestype3SWtrans}). In fact the the p-values of the variables increased considerably with the transformation, however, they still lie below the alpha level.

The test on the transformed glass type 5 data shows that, in addition to refractive index (RI), Sodium (Na), Silicon (Si), and Calcium (Ca), now for Aluminium (Al) and Potassium (K) a normal distribution cannot be rejected any more (see table \ref{tab:testrestype6SWtrans}).

Furthermore for glass type 6 the p-values increase significantly as well, except for Silicon (Si) which only slightly increases (see table \ref{tab:testrestype6SWtrans}). Consequently, $H_0$ is, analogously to the original data, not rejected for Aluminium (Al), Silicon (Si), and Calcium (Ca), plus the refractive index (RI) for which $H_0$ cannot be rejected after the transformation.

The test results of the transformed glass type 7 data show that for Aluminium (Al) the Null hypothesis still cannot be rejected. Due to contained zero-values Barium (Ba) is excluded from the transformation (see section \ref{sec:testing-transformed-data}) and therefore nothing is concluded about this specific variable. Furthermore, the result shows that the p-values of Sodium (Na) and Calcium (Ca) considerably increase and exceed the 1\, \% significance level after the transformation.

In a nutshell, the Shapiro-Wilk test shows shows significant improvements towards a normal distribution of the variables when the Box-Cox-transformation is used and the different glass types are analysed separately. Analysing the full dataset also shows some minor improvements of the p-values, however, $H_0$ is still rejected at the chosen significance level. An explanation for this result could be that in the full dataset different distributions of the different distinctive glass types are combined and therefore the Box-Cox-transformation does not improve the distribution (see section \ref{sec:boxcox-theory}).







\subsubsection{Pearson's chi-squared test}
Although for all variables for which a transformation is possible the p-value is higher than for the non-transformed data, the hypothesis of normality is still rejected for the whole sample (table \ref{tab:chi-full-trans}). The data of all types of glass is presumably too heterogenuous so that it comprises samples from several distributions within the overall sample of particular variables.

Concerning the transformation of type 1 glass, for two more variables (Al and Ca) the hypothesis of normality now cannot be rejected (table \ref{tab:chi-type1-trans}). In both cases, the p-value increases substantially through the Box-Cox-transformation. For the variable Calcium, the frequencies of the original data are slightly shifted to lower values (figure \ref{fig:chisqType1Ca}) whereas the transformation fits the data approximately to an according normal distribution (figure \ref{fig:chisqType1CaTrans}).

\begin{figure}[h!]
\centering
\includegraphics[width=0.8\textwidth]{report-chisqType1Ca}
\caption{Histogram of observed densities (red) and expected densities (blue) within the classes for the variable Calcium of type 1 glass}
\label{fig:chisqType1Ca}
\end{figure}

\begin{figure}[h!]
\centering
\includegraphics[width=0.8\textwidth]{report-chisqType1CaTrans}
\caption{Histogram of observed densities (red) and expected densities (blue) within the classes for transformed values of the variable Calcium of type 1 glass}
\label{fig:chisqType1CaTrans}
\end{figure}



Similar effects can be observed for the results of type 2 glass (table \ref{tab:chi-type2-trans}). Here, the hypothesis of normality is additionally not rejected for the variable Sodium.


For the observations of type 7 glass, the test can now even be conducted on data of the variable Sodium, which were not properly distributed to perform the test before, \ie the data were not divided into a sufficient number of classes (table \ref{tab:chi-type7-trans}).

\subsubsection{Kolmogorov-Smirnov test}

%<<calculatKSTrans, eval=TRUE, term=TRUE ,echo=FALSE>>=
%testresultKS.full.trans = apply(transformDataFrame(Glass[, -10]), 2, KSimpr.test.norm, sig=0.01)
%@
Since in the KS test of the original dataset the null hypotheses was only rejected for the variables Magnesium (Mg), Potassium (K), Barium (Ba), and Iron (Fe), transforming the data would aim at achieving a normal distribution for these four variables. However, exactly these four the transformation is not possible (see section \ref{sec:testing-transformed-data}). Therefore KS testing the transformed data will not provide further insights.

%The results are shown in table \ref{tab:KS-full}.

%\begin{table}[h!]
%\centering
%<<testresKSFullTrans, echo=FALSE, term=TRUE, results=tex>>=
%cat("\\begin{tabular}{|cccccc|} ")
%cat("\\hline ")
%cat(paste("variable & test statistic & sig. level & critical value & p-value & rejected\\\\ ", "\n", sep=""))
%cat("\\hline ")
%tr=testresultKS.full.trans
%
%for(i in 1:(length(tr))) {
%  cat(paste(
%    names(tr[i]),
%    round(tr[i][[1]]$teststat, 2),
%    0.01,
%    round(tr[i][[1]]$critical_value, 2),
%    ifelse(tr[i][[1]]$p_value < 1e-15, "< 1.0e-15", tr[i][[1]]$p_value),
%    ifelse(tr[i][[1]]$rejected, "yes", "no"),
%           sep=" & "), "\\\\ ", "\n", sep="")
%}
%
%cat("\\hline ")
%cat(paste("\\end{tabular}", "\n", sep=""))
%@
%\caption{Test results of the improved KS test on the whole transformed data
%sample with ten initial classes}
%\label{tab:KS-fullTrans}
%\end{table}
\subsection{Contour plots of selected variables}

The search for bivariate normally distributed variables shall be now demonstrated by an example from the Glass sample. Concerning the complete sample, the p-values for the variables Na and Al are highest among all used test methods. Therefore, these two variables are selected for the contour plot (\ref{fig:contourGlassNaAl}).

\begin{figure}[h!]
\centering
\includegraphics[width=0.6\textwidth]{report-contourGlassNaAl}
\caption{Data plot with contour lines of the variables Na and Al of the whole sample}
\label{fig:contourGlassNaAl}
\end{figure}


From the shape of the plot, no clear insight can be deducted about multivariate normality. In the center, the contour lines have an elliptical shape whereas an accumulation of data points can be observed at the upper right corner. This accumulation is presumably due to different distributions of variables among particular glass types. Indeed, it can be ascribed to the data of type 7 glass, which can be seen in figure \ref{fig:cluster7}.

\begin{figure}[h!]
\centering
\includegraphics[width=0.6\textwidth]{report-cluster7}
\caption{Data plot of the variables Na and Al of the whole sample. Data points of type 7 glass are highlighted in red.}
\label{fig:cluster7}
\end{figure}

If the same plot is drawn for the whole sample without data of type 7 glass (figure \ref{fig:contourGlassNaAl-7}), an elliptical shape is recognisable, except for some outliers. Quantitative tests should be conducted next in order to make a more accurate point about the compliance of the data with a multivariate normal distribution.

\begin{figure}[h!]
\centering
\includegraphics[width=0.6\textwidth]{report-contourGlassNaAl-7}
\caption{Data plot with contour lines of the variables Na and Al of the whole sample except data of type 7 glass}
\label{fig:contourGlassNaAl-7}
\end{figure}


\newpage
\section{Conclusion}\label{sec:conclusion}







%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% appendix

\newpage

\begin{appendix}
\pagenumbering{roman}		%% roman page numbers for the appendix



\section{Appendix}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 86.4 & 0.01 & 20.09 & 2.44249065417534e-15 & yes\\ 
Na & 49.04 & 0.01 & 23.21 & 3.99921126548186e-07 & yes\\ 
Mg & 668.81 & 0.01 & 16.81 & < 1.0e-15 & yes\\ 
Al & 61.72 & 0.01 & 29.14 & 5.84218540211623e-08 & yes\\ 
Si & 92.86 & 0.01 & 23.21 & 1.4432899320127e-15 & yes\\ 
K & 178.04 & 0.01 & 11.34 & < 1.0e-15 & yes\\ 
Ca & 149.63 & 0.01 & 18.48 & < 1.0e-15 & yes\\ 
Ba & 301.07 & 0.01 & 11.34 & < 1.0e-15 & yes\\ 
Fe & 137.37 & 0.01 & 18.48 & < 1.0e-15 & yes\\ \hline \end{tabular}\caption{Test results of the chi-squared test on the whole data sample with 30 initial classes}
\label{tab:chi-full-30}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 102 & 0.01 & 13.28 & < 1.0e-15 & yes\\ 
Na & 16.61 & 0.01 & 18.48 & 0.0200763340092525 & no\\ 
Mg & 28.9 & 0.01 & 16.81 & 6.36733763034192e-05 & yes\\ 
Al & 27.56 & 0.01 & 16.81 & 0.000113486165164822 & yes\\ 
Si & 35.74 & 0.01 & 15.09 & 1.07201048937799e-06 & yes\\ 
K & 129.69 & 0.01 & 18.48 & < 1.0e-15 & yes\\ 
Ca & 20.22 & 0.01 & 18.48 & 0.00510775321781454 & yes\\ 
Fe & 45.28 & 0.01 & 9.21 & 1.46922363164492e-10 & yes\\ \hline \end{tabular}\caption{Test results of the chi-squared test on type 1 glass with 30 initial classes}
\label{tab:chi-type1-30}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 77.84 & 0.01 & 15.09 & 2.33146835171283e-15 & yes\\ 
Na & 17.26 & 0.01 & 18.48 & 0.0157897896300554 & no\\ 
Mg & 306.84 & 0.01 & 15.09 & < 1.0e-15 & yes\\ 
Al & 20.77 & 0.01 & 20.09 & 0.00778471801730796 & yes\\ 
Si & 13.38 & 0.01 & 16.81 & 0.0374408380909446 & no\\ 
K & 54.24 & 0.01 & 13.28 & 4.67884619936854e-11 & yes\\ 
Ca & 106.11 & 0.01 & 11.34 & < 1.0e-15 & yes\\ 
Fe & 49.63 & 0.01 & 11.34 & 9.60126422810959e-11 & yes\\ \hline \end{tabular}\caption{Test results of the chi-squared test on type 2 glass with 30 initial classes}
\label{tab:chi-type2-30}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 22.42 & 0.01 & 6.63 & 2.18961874765e-06 & yes\\ 
Na & 12.16 & 0.01 & 6.63 & 0.000489125271576851 & yes\\ 
Al & 3.37 & 0.01 & 9.21 & 0.185460070738202 & no\\ 
Si & 21.68 & 0.01 & 6.63 & 3.2242744996136e-06 & yes\\ 
K & 15.8 & 0.01 & NA & NA & NA\\ 
Ca & 11.55 & 0.01 & NA & NA & NA\\ 
Ba & 19.75 & 0.01 & 9.21 & 5.14515780526414e-05 & yes\\ \hline \end{tabular}\caption{Test results of the chi-squared test on type 7 glass with 30 initial classes}
\label{tab:chi-type7-30}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & NA & NA & NA & NA & NA\\ 
Na & 0.95 & 0.01 & NA & 8.75605777309153e-07 & yes\\ 
Mg & NA & NA & NA & NA & NA\\ 
Al & 0.97 & 0.01 & NA & 0.000244326513056066 & yes\\ 
Si & 0.93 & 0.01 & NA & 1.58998125691823e-08 & yes\\ 
K & NA & NA & NA & NA & NA\\ 
Ca & 0.89 & 0.01 & NA & 1.13880689831982e-11 & yes\\ 
Ba & NA & NA & NA & NA & NA\\ 
Fe & NA & NA & NA & NA & NA\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the whole transformed data sample}
\label{tab:testresFullSWtrans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.89 & 0.01 & NA & 1.62433657125306e-05 & yes\\ 
Na & 0.98 & 0.01 & NA & 0.353792914291578 & no\\ 
Mg & 0.83 & 0.01 & NA & 1.40023833110547e-07 & yes\\ 
Al & 0.96 & 0.01 & NA & 0.0459207068393172 & no\\ 
Si & 0.94 & 0.01 & NA & 0.00269629206710463 & yes\\ 
K & NA & NA & NA & NA & NA\\ 
Ca & 0.97 & 0.01 & NA & 0.148237775100495 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the transformed type 1 glass}
\label{tab:testrestype1SWtrans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & NA & NA & NA & NA & NA\\ 
Na & 0.94 & 0.01 & NA & 0.00209380292451352 & yes\\ 
Mg & NA & NA & NA & NA & NA\\ 
Al & 0.98 & 0.01 & NA & 0.180941341568135 & no\\ 
Si & 0.95 & 0.01 & NA & 0.00272685181069014 & yes\\ 
K & NA & NA & NA & NA & NA\\ 
Ca & 0.91 & 0.01 & NA & 4.61802518307857e-05 & yes\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the transformed type 2 glass}
\label{tab:testrestype2SWtrans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & NA & NA & NA & NA & NA\\ 
Na & 0.96 & 0.01 & NA & 0.64635351843862 & no\\ 
Mg & 0.95 & 0.01 & NA & 0.528768845683765 & no\\ 
Al & 0.96 & 0.01 & NA & 0.600570237058731 & no\\ 
Si & 0.93 & 0.01 & NA & 0.249637851485608 & no\\ 
K & NA & NA & NA & NA & NA\\ 
Ca & 0.97 & 0.01 & NA & 0.770271104449462 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the transformed type 3 glass}
\label{tab:testrestype3SWtrans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.94 & 0.01 & NA & 0.514552235425043 & no\\ 
Na & 0.94 & 0.01 & NA & 0.507118972628293 & no\\ 
Mg & NA & NA & NA & NA & NA\\ 
Al & 0.93 & 0.01 & NA & 0.340672646826333 & no\\ 
Si & 0.95 & 0.01 & NA & 0.593358086962012 & no\\ 
K & 0.95 & 0.01 & NA & 0.547078669634891 & no\\ 
Ca & 0.92 & 0.01 & NA & 0.2231352980081 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the transformed type 5 glass}
\label{tab:testrestype5SWtrans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 0.87 & 0.01 & NA & 0.126757540911585 & no\\ 
Na & NA & NA & NA & NA & NA\\ 
Mg & NA & NA & NA & NA & NA\\ 
Al & 0.92 & 0.01 & NA & 0.377444331641712 & no\\ 
Si & 0.8 & 0.01 & NA & 0.0180983710066516 & no\\ 
Ca & 0.95 & 0.01 & NA & 0.729143379606271 & no\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the transformed type 6 glass}
\label{tab:testrestype6SWtrans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & NA & NA & NA & NA & NA\\ 
Na & 0.95 & 0.01 & NA & 0.213808937207852 & no\\ 
Al & 0.96 & 0.01 & NA & 0.430838611416679 & no\\ 
Si & 0.81 & 0.01 & NA & 0.000142333041740501 & yes\\ 
Ca & 0.93 & 0.01 & NA & 0.0686924536083304 & no\\ 
Ba & NA & NA & NA & NA & NA\\ \hline \end{tabular}\caption{Test results of the Shapiro-Wilk test on the transformed type 7 glass}
\label{tab:testrestype7SWtrans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & NA & 0.01 & NA & NA & NA\\ 
Na & 29.94 & 0.01 & 9.21 & 3.14878793927775e-07 & yes\\ 
Mg & NA & 0.01 & NA & NA & NA\\ 
Al & 24.44 & 0.01 & 18.48 & 0.000953232079632826 & yes\\ 
Si & 34 & 0.01 & 13.28 & 7.44688283815798e-07 & yes\\ 
K & NA & 0.01 & NA & NA & NA\\ 
Ca & 44.87 & 0.01 & 11.34 & 9.8475638754536e-10 & yes\\ 
Ba & NA & 0.01 & NA & NA & NA\\ 
Fe & NA & 0.01 & NA & NA & NA\\ \hline \end{tabular}\caption{Test results of the chi-squared test on the whole transformed data sample with ten initial classes}
\label{tab:chi-full-trans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & 27.81 & 0.01 & 6.63 & 1.33864150764218e-07 & yes\\ 
Na & 1.59 & 0.01 & 13.28 & 0.810360513797024 & no\\ 
Mg & 17.87 & 0.01 & NA & NA & NA\\ 
Al & 6.41 & 0.01 & 11.34 & 0.093110657016404 & no\\ 
Si & 16.87 & 0.01 & 13.28 & 0.00205136639513992 & yes\\ 
K & NA & 0.01 & NA & NA & NA\\ 
Ca & 3.35 & 0.01 & 11.34 & 0.341234021909645 & no\\ 
Fe & NA & 0.01 & NA & NA & NA\\ \hline \end{tabular}\caption{Test results of the chi-squared test on the transformed data of type 1 glass with ten initial classes}
\label{tab:chi-type1-trans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & NA & 0.01 & NA & NA & NA\\ 
Na & 4.56 & 0.01 & 9.21 & 0.102375873496938 & no\\ 
Mg & NA & 0.01 & NA & NA & NA\\ 
Al & 2.61 & 0.01 & 13.28 & 0.62553471134666 & no\\ 
Si & 2.37 & 0.01 & 6.63 & 0.123314180710608 & no\\ 
K & NA & 0.01 & NA & NA & NA\\ 
Ca & 15.61 & 0.01 & 6.63 & 7.78625904057639e-05 & yes\\ 
Fe & NA & 0.01 & NA & NA & NA\\ \hline \end{tabular}\caption{Test results of the chi-squared test on the transformed data of type 2 glass with ten initial classes}
\label{tab:chi-type2-trans}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{|cccccc|} \hline variable & test statistic & sig. level & critical value & p-value & rejected\\ \hline RI & NA & 0.01 & NA & NA & NA\\ 
Na & 1.83 & 0.01 & 6.63 & 0.176007215391275 & no\\ 
Al & 1.53 & 0.01 & 9.21 & 0.465771718543797 & no\\ 
Si & 12.46 & 0.01 & NA & NA & NA\\ 
K & NA & 0.01 & NA & NA & NA\\ 
Ca & 2.39 & 0.01 & NA & NA & NA\\ 
Ba & NA & 0.01 & NA & NA & NA\\ \hline \end{tabular}\caption{Test results of the chi-squared test on the transformed data of type 7 glass with ten initial classes}
\label{tab:chi-type7-trans}
\end{table}

\end{appendix}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% lists of figures and tables

\newpage
\listoffigures
\listoftables

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% bibliography (if needed)

%\nocite{*}
   \begin{thebibliography}{99}
    \bibitem{ucl} Bache, K., Lichman, M. (2013), UCI Machine Learning Repository, URL: \texttt{http://archive.ics.uci.edu/ml/datasets/Glass+Identification},  Irvine, CA, University of California, School of Information and Computer Science. 
    \bibitem{De02} DeGroot, Morris, H., Mark, J. (2003) Probability and
    Statistics. 3rd ed. Boston, MA: Addison-Wesley.
    \bibitem{steel} Steel, R.G.D., Torrie, J.H. (1960), Principles and Procedures of Statistics with Special Reference to the Biological Sciences, McGraw Hill, p. 350.
    
  \end{thebibliography}
\end{document}
